### ISSUE TITLE
Intermediate Contract Support

### ISSUE THREAD

**Issue by Qkyrie** [Cindercloud/Cindercloud#52]
Before supporting full-blown ABIs, we'll add the possibility to Decode functions we already know the hash of.

https://tokenstandard.codetract.io/

-> Start with tokens only
-> Transfers should be recognized as transfers. Hook can be written when a transfer is fetched to also fetch the Logs

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/44/badge)](https://dev-web.fundrequest.io/requests/44) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #44`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/44/badge)](https://dev-web.fundrequest.io/requests/44) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Qkyrie for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/44).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
